'use client'
import { GlobalStyle } from '@/styles/global-styles'
import { ThemeProvider } from 'styled-components'
import { theme } from '@/styles/theme'

// Compoents
import Header from '@/components/Header/inde'

// Font
import { Plus_Jakarta_Sans } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const PlusJakartaSans = Plus_Jakarta_Sans({
  weight: ['200', '300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={PlusJakartaSans.className}>
        <ThemeProvider theme={theme}>
          <Header />
          {children}      
          <GlobalStyle />  
        </ThemeProvider>
      </body>
    </html>
  )
}
